'use client';

import { useState, useTransition } from 'react';
import { useForm, useFieldArray, type SubmitHandler } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { db } from '@/lib/firebase';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { z } from 'zod';
import { getPersonalizedFeedback, type PersonalizedFeedbackOutput } from '@/ai/flows/personalized-feedback';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import PageHeader from '@/components/shared/PageHeader';
import { Loader2, PlusCircle, Trash2, BotMessageSquare, Dumbbell, MinusCircle } from 'lucide-react';
import type { WorkoutLog, FitnessLevel } from '@/lib/types';
import { EXERCISE_LIBRARY_DATA } from '@/lib/constants';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const setLogSchema = z.object({
  reps: z.coerce.number().min(0, "Reps must be a non-negative number"),
  weight: z.coerce.number().optional(),
  rpe: z.coerce.number().min(1, "RPE must be between 1 and 10").max(10, "RPE must be between 1 and 10").optional(),
});

const exerciseLogSchema = z.object({
  exerciseId: z.string().min(1, "Please select an exercise"),
  exerciseName: z.string(),
  sets: z.array(setLogSchema).min(1, "Add at least one set"),
  notes: z.string().optional(),
});

const workoutLogFormSchema = z.object({
  date: z.string().refine((date) => !isNaN(Date.parse(date)), { message: "Invalid date" }),
  exercises: z.array(exerciseLogSchema).min(1, "Add at least one exercise"),
  overallRPE: z.coerce.number().min(1).max(10).optional(),
  durationMinutes: z.coerce.number().min(1, "Duration must be positive").optional(),
  notes: z.string().optional(),
  fitnessGoals: z.string().min(3, "Fitness goals are needed for feedback."),
  fitnessLevel: z.enum(['Beginner', 'Intermediate', 'Advanced'])
});

type WorkoutLogFormValues = z.infer<typeof workoutLogFormSchema>;

export default function LogWorkoutPage() {
  const [feedback, setFeedback] = useState<PersonalizedFeedbackOutput | null>(null);
  const [isLogging, startLoggingTransition] = useTransition();
  const [isFetchingFeedback, startFeedbackTransition] = useTransition();
  const { toast } = useToast();

  const form = useForm<WorkoutLogFormValues>({
    resolver: zodResolver(workoutLogFormSchema),
    defaultValues: {
      date: new Date().toISOString().split('T')[0],
      exercises: [{ exerciseId: '', exerciseName: '', sets: [{ reps: 10, weight: 0, rpe: 7 }], notes: '' }],
      overallRPE: 7,
      durationMinutes: 45,
      notes: '',
      fitnessGoals: 'General fitness and strength',
      fitnessLevel: 'Intermediate',
    },
  });

  const { fields: exerciseFields, append: appendExercise, remove: removeExercise } = useFieldArray({
    control: form.control,
    name: "exercises",
  });

  const onSubmit: SubmitHandler<WorkoutLogFormValues> = (data) => {
    startLoggingTransition(async () => {
      const newLogBase: Omit<WorkoutLog, 'id' | 'createdAt'> = { // id will be auto-generated by Firestore, createdAt added below
        date: data.date,
        exercises: data.exercises.map(ex => ({
          ...ex,
          exerciseName: EXERCISE_LIBRARY_DATA.find(e => e.id === ex.exerciseId)?.name || 'Unknown Exercise'
        })),
        overallRPE: data.overallRPE,
        durationMinutes: data.durationMinutes,
        notes: data.notes,
      };

      const firestoreLogData = {
        ...newLogBase,
        createdAt: serverTimestamp(),
      };

      try {
        await addDoc(collection(db, 'workoutlogs'), firestoreLogData);
        toast({
          title: 'Workout Logged!',
          description: 'Great job on completing your workout.',
        });
      } catch (error) {
        console.error('Error saving workout log: ', error);
        toast({
          title: 'Error Logging Workout',
          description: 'Failed to save workout log. Please try again.',
          variant: 'destructive',
        });
      }
    });
  };

  const handleGetFeedback = () => {
    const data = form.getValues();
    if (!data.exercises.length || data.exercises.some(ex => !ex.exerciseId)) {
      toast({ title: 'Cannot get feedback', description: 'Please log at least one exercise and select an exercise for each entry.', variant: 'destructive' });
      return;
    }
    
    const workoutLogString = data.exercises.map(ex => 
      `${EXERCISE_LIBRARY_DATA.find(e => e.id === ex.exerciseId)?.name || ex.exerciseName}:\n` +
      ex.sets.map((s, i) => `  Set ${i+1}: ${s.reps} reps${s.weight ? ` @ ${s.weight}kg` : ''}${s.rpe ? `, RPE ${s.rpe}` : ''}`).join('\n') +
      (ex.notes ? `\n  Notes: ${ex.notes}` : '')
    ).join('\n\n');

    const feedbackInput = {
      workoutLog: `Date: ${data.date}\nDuration: ${data.durationMinutes || 'N/A'} min\nOverall RPE: ${data.overallRPE || 'N/A'}\n\nExercises:\n${workoutLogString}\n\nOverall Notes: ${data.notes || 'None'}`,
      fitnessGoals: data.fitnessGoals,
      level: data.fitnessLevel,
    };

    startFeedbackTransition(async () => {
      try {
        setFeedback(null);
        const result = await getPersonalizedFeedback(feedbackInput);
        setFeedback(result);
        toast({
          title: 'Feedback Ready!',
          description: 'Your personalized AI feedback has been generated.',
        });
      } catch (error) {
        console.error('Error getting feedback:', error);
        toast({
          title: 'Error',
          description: 'Failed to get feedback. Please try again.',
          variant: 'destructive',
        });
      }
    });
  };
  
  const handleExerciseChange = (value: string, index: number) => {
    const selectedExercise = EXERCISE_LIBRARY_DATA.find(ex => ex.id === value);
    if (selectedExercise) {
      form.setValue(`exercises.${index}.exerciseName`, selectedExercise.name);
      form.setValue(`exercises.${index}.exerciseId`, selectedExercise.id);
    }
  };

  return (
    <div className="flex flex-col gap-6">
      <PageHeader title="Log Your Workout" description="Keep track of your efforts and progress." />
      
      <Card>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)}>
            <CardHeader>
              <CardTitle>Workout Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <FormField
                  control={form.control}
                  name="date"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Date</FormLabel>
                      <FormControl>
                        <Input type="date" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                 <FormField
                  control={form.control}
                  name="durationMinutes"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Duration (minutes)</FormLabel>
                      <FormControl>
                        <Input type="number" placeholder="e.g., 45" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <div>
                <FormLabel className="text-lg font-semibold mb-2 block">Exercises</FormLabel>
                {exerciseFields.map((exerciseEntry, exerciseIndex) => {
                  const { fields: setFields, append: appendSet, remove: removeSet } = useFieldArray({
                    control: form.control,
                    name: `exercises.${exerciseIndex}.sets` as const,
                  });

                  return (
                    <Card key={exerciseEntry.id} className="mt-4 p-4 space-y-4">
                      <div className="flex justify-between items-center">
                         <FormField
                          control={form.control}
                          name={`exercises.${exerciseIndex}.exerciseId`}
                          render={({ field: exerciseField }) => (
                            <FormItem className="flex-grow mr-2">
                              <FormLabel className="sr-only">Exercise</FormLabel>
                              <Select 
                                onValueChange={(value) => handleExerciseChange(value, exerciseIndex)} 
                                defaultValue={exerciseField.value}
                              >
                                <FormControl>
                                  <SelectTrigger>
                                    <SelectValue placeholder="Select Exercise" />
                                  </SelectTrigger>
                                </FormControl>
                                <SelectContent>
                                  {EXERCISE_LIBRARY_DATA.map(ex => (
                                    <SelectItem key={ex.id} value={ex.id}>{ex.name}</SelectItem>
                                  ))}
                                </SelectContent>
                              </Select>
                              <FormMessage />
                            </FormItem>
                          )}
                        />
                        <Button type="button" variant="ghost" size="icon" onClick={() => removeExercise(exerciseIndex)} disabled={exerciseFields.length <= 1}>
                          <Trash2 className="h-4 w-4 text-destructive" />
                        </Button>
                      </div>
                      
                      <div className="space-y-3">
                        <FormLabel>Sets</FormLabel>
                        {setFields.map((setEntry, setIndex) => (
                          <div key={setEntry.id} className="flex flex-col sm:flex-row gap-2 items-start sm:items-end p-3 border rounded-md">
                            <span className="text-sm font-medium text-muted-foreground sm:mr-2">Set {setIndex + 1}</span>
                            <FormField
                              control={form.control}
                              name={`exercises.${exerciseIndex}.sets.${setIndex}.reps`}
                              render={({ field }) => (
                                <FormItem className="flex-1 min-w-[60px]">
                                  <FormLabel className="text-xs">Reps</FormLabel>
                                  <FormControl><Input type="number" placeholder="0" {...field} /></FormControl>
                                  <FormMessage />
                                </FormItem>
                              )}
                            />
                            <FormField
                              control={form.control}
                              name={`exercises.${exerciseIndex}.sets.${setIndex}.weight`}
                              render={({ field }) => (
                                <FormItem className="flex-1 min-w-[60px]">
                                  <FormLabel className="text-xs">Weight (kg)</FormLabel>
                                  <FormControl><Input type="number" placeholder="0" {...field} /></FormControl>
                                  <FormMessage />
                                </FormItem>
                              )}
                            />
                            <FormField
                              control={form.control}
                              name={`exercises.${exerciseIndex}.sets.${setIndex}.rpe`}
                              render={({ field }) => (
                                <FormItem className="flex-1 min-w-[60px]">
                                  <FormLabel className="text-xs">RPE (1-10)</FormLabel>
                                  <FormControl><Input type="number" min="1" max="10" placeholder="7" {...field} /></FormControl>
                                  <FormMessage />
                                </FormItem>
                              )}
                            />
                            <Button type="button" variant="ghost" size="icon" onClick={() => removeSet(setIndex)} disabled={setFields.length <= 1}>
                              <MinusCircle className="h-4 w-4 text-muted-foreground hover:text-destructive" />
                            </Button>
                          </div>
                        ))}
                        <Button type="button" variant="outline" size="sm" onClick={() => appendSet({ reps: 0, weight: 0, rpe: 7 })}>
                          <PlusCircle className="mr-2 h-4 w-4" /> Add Set
                        </Button>
                      </div>

                       <FormField
                        control={form.control}
                        name={`exercises.${exerciseIndex}.notes`}
                        render={({ field: notesField }) => (
                          <FormItem>
                            <FormLabel>Exercise Notes (Optional)</FormLabel>
                            <FormControl>
                              <Textarea placeholder="e.g., Felt strong, focus on form next time" {...notesField} />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </Card>
                  );
                })}
                <Button type="button" variant="outline" size="sm" onClick={() => appendExercise({ exerciseId: '', exerciseName: '', sets: [{ reps: 10, weight: 0, rpe: 7 }], notes: '' })} className="mt-4">
                  <PlusCircle className="mr-2 h-4 w-4" /> Add Exercise
                </Button>
              </div>

              <FormField
                control={form.control}
                name="overallRPE"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Overall RPE (1-10)</FormLabel>
                    <FormControl>
                      <Input type="number" min="1" max="10" placeholder="e.g., 8" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="notes"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Overall Workout Notes (Optional)</FormLabel>
                    <FormControl>
                      <Textarea placeholder="e.g., Good session, felt a bit tired." {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <Card className="mt-4 p-4 bg-muted/50">
                 <CardTitle className="text-md mb-2">For AI Feedback</CardTitle>
                 <FormField
                    control={form.control}
                    name="fitnessGoals"
                    render={({ field }) => (
                      <FormItem className="mb-4">
                        <FormLabel>Your Current Fitness Goals</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., Build muscle and increase endurance" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="fitnessLevel"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Your Current Fitness Level</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger>
                              <SelectValue placeholder="Select your fitness level" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="Beginner">Beginner</SelectItem>
                            <SelectItem value="Intermediate">Intermediate</SelectItem>
                            <SelectItem value="Advanced">Advanced</SelectItem>
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
              </Card>

            </CardContent>
            <CardFooter className="flex flex-col sm:flex-row gap-2">
              <Button type="submit" disabled={isLogging} className="w-full sm:w-auto">
                {isLogging ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Dumbbell className="mr-2 h-4 w-4" /> }
                Log Workout
              </Button>
              <Button 
                type="button" 
                variant="outline" 
                onClick={handleGetFeedback} 
                disabled={isFetchingFeedback || form.getValues().exercises.length === 0 || form.getValues().exercises.some(ex => !ex.exerciseId)} 
                className="w-full sm:w-auto"
              >
                 {isFetchingFeedback ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <BotMessageSquare className="mr-2 h-4 w-4" /> }
                Get AI Feedback
              </Button>
            </CardFooter>
          </form>
        </Form>
      </Card>

      {(isFetchingFeedback && !feedback) && (
        <Card>
          <CardContent className="p-6 flex flex-col items-center justify-center min-h-[150px]">
            <Loader2 className="h-10 w-10 animate-spin text-primary mb-3" />
            <p className="text-muted-foreground">Generating your AI feedback...</p>
          </CardContent>
        </Card>
      )}

      {feedback && (
        <Card>
          <CardHeader>
            <CardTitle>Personalized AI Feedback</CardTitle>
          </CardHeader>
          <CardContent>
            <pre className="whitespace-pre-wrap text-sm bg-muted p-4 rounded-md overflow-x-auto">
              {feedback.feedback}
            </pre>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
